name: TF20
channels: !!python/tuple
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - absl-py==0.9.0
  - astor==0.8.1
  - attrs==19.3.0
  - backcall==0.2.0
  - bleach==3.1.5
  - cycler==0.10.0
  - decorator==4.4.2
  - defusedxml==0.6.0
  - entrypoints==0.3
  - gast==0.3.3
  - google-pasta==0.2.0
  - grpcio==1.30.0
  - h5py==2.10.0
  - importlib-metadata==1.7.0
  - ipykernel==5.3.2
  - ipython==7.16.1
  - ipython-genutils==0.2.0
  - ipywidgets==7.5.1
  - jedi==0.17.1
  - jinja2==2.11.2
  - jsonschema==3.2.0
  - jupyter==1.0.0
  - jupyter-client==6.1.6
  - jupyter-console==6.1.0
  - jupyter-core==4.6.3
  - keras==2.3.1
  - keras-applications==1.0.8
  - keras-preprocessing==1.1.2
  - kiwisolver==1.2.0
  - markdown==3.2.2
  - markupsafe==1.1.1
  - matplotlib==3.2.2
  - mistune==0.8.4
  - nbconvert==5.6.1
  - nbformat==5.0.7
  - notebook==6.0.3
  - numpy==1.19.0
  - packaging==20.4
  - pandas==1.0.5
  - pandocfilters==1.4.2
  - parso==0.7.0
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==7.2.0
  - prometheus-client==0.8.0
  - prompt-toolkit==3.0.5
  - protobuf==3.12.2
  - ptyprocess==0.6.0
  - pydot==1.4.1
  - pygments==2.6.1
  - pyparsing==2.4.7
  - pyrsistent==0.16.0
  - python-dateutil==2.8.1
  - pytz==2020.1
  - pyyaml==5.3.1
  - pyzmq==19.0.1
  - qtconsole==4.7.5
  - qtpy==1.9.0
  - runipy==0.1.5
  - scipy==1.5.1
  - send2trash==1.5.0
  - six==1.15.0
  - tb-nightly==1.14.0a20190603
  - tensorflow-gpu==2.0.0b1
  - termcolor==1.1.0
  - terminado==0.8.3
  - testpath==0.4.4
  - tf-estimator-nightly==1.14.0.dev2019060501
  - tornado==6.0.4
  - traitlets==4.3.3
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - werkzeug==1.0.1
  - widgetsnbextension==3.5.1
  - wrapt==1.12.1
  - zipp==3.1.0
prefix: /root/anaconda/envs/TF20

